// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT
#![allow(deprecated)]

use crate::{ffi,Device,Object};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "NMDeviceMacvlan")]
    pub struct DeviceMacvlan(Object<ffi::NMDeviceMacvlan, ffi::NMDeviceMacvlanClass>) @extends Device, Object;

    match fn {
        type_ => || ffi::nm_device_macvlan_get_type(),
    }
}

impl DeviceMacvlan {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceMacvlan`] objects.
            ///
            /// This method returns an instance of [`DeviceMacvlanBuilder`](crate::builders::DeviceMacvlanBuilder) which can be used to create [`DeviceMacvlan`] objects.
            pub fn builder() -> DeviceMacvlanBuilder {
                DeviceMacvlanBuilder::new()
            }
        

    #[cfg_attr(feature = "v1_24", deprecated = "Since 1.24")]
    #[allow(deprecated)]
    #[doc(alias = "nm_device_macvlan_get_hw_address")]
    #[doc(alias = "get_hw_address")]
    pub fn hw_address(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_device_macvlan_get_hw_address(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_macvlan_get_mode")]
    #[doc(alias = "get_mode")]
    pub fn mode(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_device_macvlan_get_mode(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_macvlan_get_no_promisc")]
    #[doc(alias = "get_no_promisc")]
    #[doc(alias = "no-promisc")]
    pub fn is_no_promisc(&self) -> bool {
        unsafe {
            from_glib(ffi::nm_device_macvlan_get_no_promisc(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_macvlan_get_parent")]
    #[doc(alias = "get_parent")]
    pub fn parent(&self) -> Device {
        unsafe {
            from_glib_none(ffi::nm_device_macvlan_get_parent(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_macvlan_get_tap")]
    #[doc(alias = "get_tap")]
    #[doc(alias = "tap")]
    pub fn is_tap(&self) -> bool {
        unsafe {
            from_glib(ffi::nm_device_macvlan_get_tap(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "mode")]
    pub fn connect_mode_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_mode_trampoline<F: Fn(&DeviceMacvlan) + 'static>(this: *mut ffi::NMDeviceMacvlan, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::mode".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_mode_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "no-promisc")]
    pub fn connect_no_promisc_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_no_promisc_trampoline<F: Fn(&DeviceMacvlan) + 'static>(this: *mut ffi::NMDeviceMacvlan, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::no-promisc".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_no_promisc_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "parent")]
    pub fn connect_parent_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_parent_trampoline<F: Fn(&DeviceMacvlan) + 'static>(this: *mut ffi::NMDeviceMacvlan, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::parent".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_parent_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "tap")]
    pub fn connect_tap_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_tap_trampoline<F: Fn(&DeviceMacvlan) + 'static>(this: *mut ffi::NMDeviceMacvlan, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::tap".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_tap_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceMacvlan`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceMacvlanBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceMacvlan>,
        }

        impl DeviceMacvlanBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn autoconnect(self, autoconnect: bool) -> Self {
                            Self { builder: self.builder.property("autoconnect", autoconnect), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceMacvlan`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceMacvlan {
assert_initialized_main_thread!();
    self.builder.build() }
}
