// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Device,Object};
use glib::{prelude::*};

glib::wrapper! {
    #[doc(alias = "NMDeviceWpan")]
    pub struct DeviceWpan(Object<ffi::NMDeviceWpan, ffi::NMDeviceWpanClass>) @extends Device, Object;

    match fn {
        type_ => || ffi::nm_device_wpan_get_type(),
    }
}

impl DeviceWpan {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceWpan`] objects.
            ///
            /// This method returns an instance of [`DeviceWpanBuilder`](crate::builders::DeviceWpanBuilder) which can be used to create [`DeviceWpan`] objects.
            pub fn builder() -> DeviceWpanBuilder {
                DeviceWpanBuilder::new()
            }
        
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceWpan`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceWpanBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceWpan>,
        }

        impl DeviceWpanBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn autoconnect(self, autoconnect: bool) -> Self {
                            Self { builder: self.builder.property("autoconnect", autoconnect), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceWpan`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceWpan {
assert_initialized_main_thread!();
    self.builder.build() }
}
