// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Device,Object};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "NMDeviceVrf")]
    pub struct DeviceVrf(Object<ffi::NMDeviceVrf, ffi::NMDeviceVrfClass>) @extends Device, Object;

    match fn {
        type_ => || ffi::nm_device_vrf_get_type(),
    }
}

impl DeviceVrf {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceVrf`] objects.
            ///
            /// This method returns an instance of [`DeviceVrfBuilder`](crate::builders::DeviceVrfBuilder) which can be used to create [`DeviceVrf`] objects.
            pub fn builder() -> DeviceVrfBuilder {
                DeviceVrfBuilder::new()
            }
        

    #[doc(alias = "nm_device_vrf_get_table")]
    #[doc(alias = "get_table")]
    pub fn table(&self) -> u32 {
        unsafe {
            ffi::nm_device_vrf_get_table(self.to_glib_none().0)
        }
    }

    #[cfg(feature = "v1_24")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_24")))]
    #[doc(alias = "table")]
    pub fn connect_table_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_table_trampoline<F: Fn(&DeviceVrf) + 'static>(this: *mut ffi::NMDeviceVrf, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::table".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_table_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceVrf`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceVrfBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceVrf>,
        }

        impl DeviceVrfBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn autoconnect(self, autoconnect: bool) -> Self {
                            Self { builder: self.builder.property("autoconnect", autoconnect), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceVrf`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceVrf {
assert_initialized_main_thread!();
    self.builder.build() }
}
