// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Device,Object};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "NMDeviceHsr")]
    pub struct DeviceHsr(Object<ffi::NMDeviceHsr, ffi::NMDeviceHsrClass>) @extends Device, Object;

    match fn {
        type_ => || ffi::nm_device_hsr_get_type(),
    }
}

impl DeviceHsr {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceHsr`] objects.
            ///
            /// This method returns an instance of [`DeviceHsrBuilder`](crate::builders::DeviceHsrBuilder) which can be used to create [`DeviceHsr`] objects.
            pub fn builder() -> DeviceHsrBuilder {
                DeviceHsrBuilder::new()
            }
        

    #[doc(alias = "nm_device_hsr_get_multicast_spec")]
    #[doc(alias = "get_multicast_spec")]
    #[doc(alias = "multicast-spec")]
    pub fn multicast_spec(&self) -> u8 {
        unsafe {
            ffi::nm_device_hsr_get_multicast_spec(self.to_glib_none().0)
        }
    }

    #[doc(alias = "nm_device_hsr_get_port1")]
    #[doc(alias = "get_port1")]
    pub fn port1(&self) -> Device {
        unsafe {
            from_glib_none(ffi::nm_device_hsr_get_port1(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_hsr_get_port2")]
    #[doc(alias = "get_port2")]
    pub fn port2(&self) -> Device {
        unsafe {
            from_glib_none(ffi::nm_device_hsr_get_port2(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_hsr_get_prp")]
    #[doc(alias = "get_prp")]
    #[doc(alias = "prp")]
    pub fn is_prp(&self) -> bool {
        unsafe {
            from_glib(ffi::nm_device_hsr_get_prp(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_hsr_get_supervision_address")]
    #[doc(alias = "get_supervision_address")]
    #[doc(alias = "supervision-address")]
    pub fn supervision_address(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_device_hsr_get_supervision_address(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v1_46")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_46")))]
    #[doc(alias = "multicast-spec")]
    pub fn connect_multicast_spec_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_multicast_spec_trampoline<F: Fn(&DeviceHsr) + 'static>(this: *mut ffi::NMDeviceHsr, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::multicast-spec".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_multicast_spec_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_46")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_46")))]
    #[doc(alias = "port1")]
    pub fn connect_port1_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_port1_trampoline<F: Fn(&DeviceHsr) + 'static>(this: *mut ffi::NMDeviceHsr, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::port1".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_port1_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_46")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_46")))]
    #[doc(alias = "port2")]
    pub fn connect_port2_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_port2_trampoline<F: Fn(&DeviceHsr) + 'static>(this: *mut ffi::NMDeviceHsr, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::port2".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_port2_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_46")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_46")))]
    #[doc(alias = "prp")]
    pub fn connect_prp_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_prp_trampoline<F: Fn(&DeviceHsr) + 'static>(this: *mut ffi::NMDeviceHsr, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::prp".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_prp_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_46")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_46")))]
    #[doc(alias = "supervision-address")]
    pub fn connect_supervision_address_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_supervision_address_trampoline<F: Fn(&DeviceHsr) + 'static>(this: *mut ffi::NMDeviceHsr, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::supervision-address".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_supervision_address_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceHsr`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceHsrBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceHsr>,
        }

        impl DeviceHsrBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn autoconnect(self, autoconnect: bool) -> Self {
                            Self { builder: self.builder.property("autoconnect", autoconnect), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceHsr`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceHsr {
assert_initialized_main_thread!();
    self.builder.build() }
}
