// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Device,IPTunnelMode,Object};
#[cfg(feature = "v1_12")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_12")))]
use crate::{IPTunnelFlags};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "NMDeviceIPTunnel")]
    pub struct DeviceIPTunnel(Object<ffi::NMDeviceIPTunnel, ffi::NMDeviceIPTunnelClass>) @extends Device, Object;

    match fn {
        type_ => || ffi::nm_device_ip_tunnel_get_type(),
    }
}

impl DeviceIPTunnel {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceIPTunnel`] objects.
            ///
            /// This method returns an instance of [`DeviceIPTunnelBuilder`](crate::builders::DeviceIPTunnelBuilder) which can be used to create [`DeviceIPTunnel`] objects.
            pub fn builder() -> DeviceIPTunnelBuilder {
                DeviceIPTunnelBuilder::new()
            }
        

    #[doc(alias = "nm_device_ip_tunnel_get_encapsulation_limit")]
    #[doc(alias = "get_encapsulation_limit")]
    #[doc(alias = "encapsulation-limit")]
    pub fn encapsulation_limit(&self) -> u8 {
        unsafe {
            ffi::nm_device_ip_tunnel_get_encapsulation_limit(self.to_glib_none().0)
        }
    }

    #[cfg(feature = "v1_12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_12")))]
    #[doc(alias = "nm_device_ip_tunnel_get_flags")]
    #[doc(alias = "get_flags")]
    pub fn flags(&self) -> IPTunnelFlags {
        unsafe {
            from_glib(ffi::nm_device_ip_tunnel_get_flags(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_flow_label")]
    #[doc(alias = "get_flow_label")]
    #[doc(alias = "flow-label")]
    pub fn flow_label(&self) -> u32 {
        unsafe {
            ffi::nm_device_ip_tunnel_get_flow_label(self.to_glib_none().0)
        }
    }

    #[cfg(feature = "v1_46")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_46")))]
    #[doc(alias = "nm_device_ip_tunnel_get_fwmark")]
    #[doc(alias = "get_fwmark")]
    pub fn fwmark(&self) -> u32 {
        unsafe {
            ffi::nm_device_ip_tunnel_get_fwmark(self.to_glib_none().0)
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_input_key")]
    #[doc(alias = "get_input_key")]
    #[doc(alias = "input-key")]
    pub fn input_key(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_device_ip_tunnel_get_input_key(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_local")]
    #[doc(alias = "get_local")]
    pub fn local(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_device_ip_tunnel_get_local(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_mode")]
    #[doc(alias = "get_mode")]
    pub fn mode(&self) -> IPTunnelMode {
        unsafe {
            from_glib(ffi::nm_device_ip_tunnel_get_mode(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_output_key")]
    #[doc(alias = "get_output_key")]
    #[doc(alias = "output-key")]
    pub fn output_key(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_device_ip_tunnel_get_output_key(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_parent")]
    #[doc(alias = "get_parent")]
    pub fn parent(&self) -> Device {
        unsafe {
            from_glib_none(ffi::nm_device_ip_tunnel_get_parent(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_path_mtu_discovery")]
    #[doc(alias = "get_path_mtu_discovery")]
    #[doc(alias = "path-mtu-discovery")]
    pub fn is_path_mtu_discovery(&self) -> bool {
        unsafe {
            from_glib(ffi::nm_device_ip_tunnel_get_path_mtu_discovery(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_remote")]
    #[doc(alias = "get_remote")]
    pub fn remote(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_device_ip_tunnel_get_remote(self.to_glib_none().0))
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_tos")]
    #[doc(alias = "get_tos")]
    pub fn tos(&self) -> u8 {
        unsafe {
            ffi::nm_device_ip_tunnel_get_tos(self.to_glib_none().0)
        }
    }

    #[doc(alias = "nm_device_ip_tunnel_get_ttl")]
    #[doc(alias = "get_ttl")]
    pub fn ttl(&self) -> u8 {
        unsafe {
            ffi::nm_device_ip_tunnel_get_ttl(self.to_glib_none().0)
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "encapsulation-limit")]
    pub fn connect_encapsulation_limit_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_encapsulation_limit_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::encapsulation-limit".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_encapsulation_limit_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_12")))]
    #[doc(alias = "flags")]
    pub fn connect_flags_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_flags_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::flags".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_flags_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "flow-label")]
    pub fn connect_flow_label_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_flow_label_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::flow-label".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_flow_label_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_46")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_46")))]
    #[doc(alias = "fwmark")]
    pub fn connect_fwmark_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_fwmark_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::fwmark".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_fwmark_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "input-key")]
    pub fn connect_input_key_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_input_key_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::input-key".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_input_key_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "local")]
    pub fn connect_local_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_local_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::local".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_local_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "mode")]
    pub fn connect_mode_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_mode_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::mode".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_mode_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "output-key")]
    pub fn connect_output_key_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_output_key_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::output-key".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_output_key_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "parent")]
    pub fn connect_parent_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_parent_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::parent".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_parent_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "path-mtu-discovery")]
    pub fn connect_path_mtu_discovery_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_path_mtu_discovery_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::path-mtu-discovery".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_path_mtu_discovery_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "remote")]
    pub fn connect_remote_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_remote_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::remote".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_remote_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "tos")]
    pub fn connect_tos_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_tos_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::tos".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_tos_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_2")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_2")))]
    #[doc(alias = "ttl")]
    pub fn connect_ttl_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_ttl_trampoline<F: Fn(&DeviceIPTunnel) + 'static>(this: *mut ffi::NMDeviceIPTunnel, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::ttl".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_ttl_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceIPTunnel`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceIPTunnelBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceIPTunnel>,
        }

        impl DeviceIPTunnelBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn autoconnect(self, autoconnect: bool) -> Self {
                            Self { builder: self.builder.property("autoconnect", autoconnect), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceIPTunnel`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceIPTunnel {
assert_initialized_main_thread!();
    self.builder.build() }
}
