// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Device,Object};
use glib::{prelude::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`DeviceExt`][trait@crate::prelude::DeviceExt], [`ObjectExt`][trait@crate::prelude::ObjectExt]
    #[doc(alias = "NMDeviceLoopback")]
    pub struct DeviceLoopback(Object<ffi::NMDeviceLoopback, ffi::NMDeviceLoopbackClass>) @extends Device, Object;

    match fn {
        type_ => || ffi::nm_device_loopback_get_type(),
    }
}

impl DeviceLoopback {
            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceLoopback`] objects.
            ///
            /// This method returns an instance of [`DeviceLoopbackBuilder`](crate::builders::DeviceLoopbackBuilder) which can be used to create [`DeviceLoopback`] objects.
            pub fn builder() -> DeviceLoopbackBuilder {
                DeviceLoopbackBuilder::new()
            }
        
}

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceLoopback`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceLoopbackBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceLoopback>,
        }

        impl DeviceLoopbackBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// Whether the device can auto-activate a connection.
                            ///
                            /// The property setter is a synchronous D-Bus call. This is deprecated since 1.22.
                            pub fn autoconnect(self, autoconnect: bool) -> Self {
                            Self { builder: self.builder.property("autoconnect", autoconnect), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceLoopback`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceLoopback {
assert_initialized_main_thread!();
    self.builder.build() }
}
