// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Setting};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    /// IPv6 prefix delegation settings
    ///
    /// ## Properties
    ///
    ///
    /// #### `subnet-id`
    ///  The subnet ID to use on the interface from the prefix delegation received via
    /// an upstream interface. Set to a value between 0 and 0xffffffff (2^32 - 1)
    /// to indicate a specific subnet ID; or set to -1 to automatically choose
    /// an available subnet ID.
    ///
    /// Readable | Writeable
    /// <details><summary><h4>Setting</h4></summary>
    ///
    ///
    /// #### `name`
    ///  The setting's name, which uniquely identifies the setting within the
    /// connection.  Each setting type has a name unique to that type, for
    /// example "ppp" or "802-11-wireless" or "802-3-ethernet".
    ///
    /// Readable
    /// </details>
    ///
    /// # Implements
    ///
    /// [`SettingExt`][trait@crate::prelude::SettingExt]
    #[doc(alias = "NMSettingPrefixDelegation")]
    pub struct SettingPrefixDelegation(Object<ffi::NMSettingPrefixDelegation, ffi::NMSettingPrefixDelegationClass>) @extends Setting;

    match fn {
        type_ => || ffi::nm_setting_prefix_delegation_get_type(),
    }
}

impl SettingPrefixDelegation {
    /// Creates a new #NMSettingPrefixDelegation object with default values.
    ///
    /// # Returns
    ///
    /// the new empty #NMSettingPrefixDelegation object
    #[doc(alias = "nm_setting_prefix_delegation_new")]
    pub fn new() -> SettingPrefixDelegation {
        assert_initialized_main_thread!();
        unsafe {
            Setting::from_glib_full(ffi::nm_setting_prefix_delegation_new()).unsafe_cast()
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`SettingPrefixDelegation`] objects.
            ///
            /// This method returns an instance of [`SettingPrefixDelegationBuilder`](crate::builders::SettingPrefixDelegationBuilder) which can be used to create [`SettingPrefixDelegation`] objects.
            pub fn builder() -> SettingPrefixDelegationBuilder {
                SettingPrefixDelegationBuilder::new()
            }
        

    ///
    /// # Returns
    ///
    /// the subnet ID for prefix delegation
    #[doc(alias = "nm_setting_prefix_delegation_get_subnet_id")]
    #[doc(alias = "get_subnet_id")]
    #[doc(alias = "subnet-id")]
    pub fn subnet_id(&self) -> i64 {
        unsafe {
            ffi::nm_setting_prefix_delegation_get_subnet_id(self.to_glib_none().0)
        }
    }

    /// The subnet ID to use on the interface from the prefix delegation received via
    /// an upstream interface. Set to a value between 0 and 0xffffffff (2^32 - 1)
    /// to indicate a specific subnet ID; or set to -1 to automatically choose
    /// an available subnet ID.
    #[cfg(feature = "v1_54")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_54")))]
    #[doc(alias = "subnet-id")]
    pub fn set_subnet_id(&self, subnet_id: i64) {
        ObjectExt::set_property(self,"subnet-id", subnet_id)
    }

    #[cfg(feature = "v1_54")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_54")))]
    #[doc(alias = "subnet-id")]
    pub fn connect_subnet_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_subnet_id_trampoline<F: Fn(&SettingPrefixDelegation) + 'static>(this: *mut ffi::NMSettingPrefixDelegation, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::subnet-id".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_subnet_id_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

#[cfg(feature = "v1_54")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_54")))]
impl Default for SettingPrefixDelegation {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`SettingPrefixDelegation`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct SettingPrefixDelegationBuilder {
            builder: glib::object::ObjectBuilder<'static, SettingPrefixDelegation>,
        }

        impl SettingPrefixDelegationBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The subnet ID to use on the interface from the prefix delegation received via
                            /// an upstream interface. Set to a value between 0 and 0xffffffff (2^32 - 1)
                            /// to indicate a specific subnet ID; or set to -1 to automatically choose
                            /// an available subnet ID.
                            #[cfg(feature = "v1_54")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_54")))]
    pub fn subnet_id(self, subnet_id: i64) -> Self {
                            Self { builder: self.builder.property("subnet-id", subnet_id), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`SettingPrefixDelegation`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> SettingPrefixDelegation {
assert_initialized_main_thread!();
    self.builder.build() }
}
