// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Setting};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    /// Link settings
    ///
    /// ## Properties
    ///
    ///
    /// #### `gro-max-size`
    ///  The maximum size of a packet built by the Generic Receive Offload stack for
    /// this device. The value must be between 0 and 4294967295. When set to -1, the
    /// existing value is preserved.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `gso-max-segments`
    ///  The maximum segments of a Generic Segment Offload packet the device should accept.
    /// The value must be between 0 and 4294967295. When set to -1, the existing value
    /// is preserved.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `gso-max-size`
    ///  The maximum size of a Generic Segment Offload packet the device should accept.
    /// The value must be between 0 and 4294967295. When set to -1, the existing value
    /// is preserved.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `tx-queue-length`
    ///  The size of the transmit queue for the device, in number of packets. The value
    /// must be between 0 and 4294967295. When set to -1, the existing value is preserved.
    ///
    /// Readable | Writeable
    /// <details><summary><h4>Setting</h4></summary>
    ///
    ///
    /// #### `name`
    ///  The setting's name, which uniquely identifies the setting within the
    /// connection.  Each setting type has a name unique to that type, for
    /// example "ppp" or "802-11-wireless" or "802-3-ethernet".
    ///
    /// Readable
    /// </details>
    ///
    /// # Implements
    ///
    /// [`SettingExt`][trait@crate::prelude::SettingExt]
    #[doc(alias = "NMSettingLink")]
    pub struct SettingLink(Object<ffi::NMSettingLink, ffi::NMSettingLinkClass>) @extends Setting;

    match fn {
        type_ => || ffi::nm_setting_link_get_type(),
    }
}

impl SettingLink {
    /// Creates a new #NMSettingLink object with default values.
    ///
    /// # Returns
    ///
    /// the new empty #NMSettingLink object
    #[doc(alias = "nm_setting_link_new")]
    pub fn new() -> SettingLink {
        assert_initialized_main_thread!();
        unsafe {
            Setting::from_glib_full(ffi::nm_setting_link_new()).unsafe_cast()
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`SettingLink`] objects.
            ///
            /// This method returns an instance of [`SettingLinkBuilder`](crate::builders::SettingLinkBuilder) which can be used to create [`SettingLink`] objects.
            pub fn builder() -> SettingLinkBuilder {
                SettingLinkBuilder::new()
            }
        

    /// Returns the value contained in the #NMSettingLink:gro-max-size
    /// property.
    ///
    /// # Returns
    ///
    /// the 'gro-max-size' property value
    #[doc(alias = "nm_setting_link_get_gro_max_size")]
    #[doc(alias = "get_gro_max_size")]
    #[doc(alias = "gro-max-size")]
    pub fn gro_max_size(&self) -> i64 {
        unsafe {
            ffi::nm_setting_link_get_gro_max_size(self.to_glib_none().0)
        }
    }

    /// Returns the value contained in the #NMSettingLink:gso-max-segments
    /// property.
    ///
    /// # Returns
    ///
    /// the 'gso-max-segments' property value
    #[doc(alias = "nm_setting_link_get_gso_max_segments")]
    #[doc(alias = "get_gso_max_segments")]
    #[doc(alias = "gso-max-segments")]
    pub fn gso_max_segments(&self) -> i64 {
        unsafe {
            ffi::nm_setting_link_get_gso_max_segments(self.to_glib_none().0)
        }
    }

    /// Returns the value contained in the #NMSettingLink:gso-max-size
    /// property.
    ///
    /// # Returns
    ///
    /// the 'gso-max-size' property value
    #[doc(alias = "nm_setting_link_get_gso_max_size")]
    #[doc(alias = "get_gso_max_size")]
    #[doc(alias = "gso-max-size")]
    pub fn gso_max_size(&self) -> i64 {
        unsafe {
            ffi::nm_setting_link_get_gso_max_size(self.to_glib_none().0)
        }
    }

    /// Returns the value contained in the #NMSettingLink:tx-queue-length
    /// property.
    ///
    /// # Returns
    ///
    /// the 'tx-queue-length' property value
    #[doc(alias = "nm_setting_link_get_tx_queue_length")]
    #[doc(alias = "get_tx_queue_length")]
    #[doc(alias = "tx-queue-length")]
    pub fn tx_queue_length(&self) -> i64 {
        unsafe {
            ffi::nm_setting_link_get_tx_queue_length(self.to_glib_none().0)
        }
    }

    /// The maximum size of a packet built by the Generic Receive Offload stack for
    /// this device. The value must be between 0 and 4294967295. When set to -1, the
    /// existing value is preserved.
    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "gro-max-size")]
    pub fn set_gro_max_size(&self, gro_max_size: i64) {
        ObjectExt::set_property(self,"gro-max-size", gro_max_size)
    }

    /// The maximum segments of a Generic Segment Offload packet the device should accept.
    /// The value must be between 0 and 4294967295. When set to -1, the existing value
    /// is preserved.
    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "gso-max-segments")]
    pub fn set_gso_max_segments(&self, gso_max_segments: i64) {
        ObjectExt::set_property(self,"gso-max-segments", gso_max_segments)
    }

    /// The maximum size of a Generic Segment Offload packet the device should accept.
    /// The value must be between 0 and 4294967295. When set to -1, the existing value
    /// is preserved.
    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "gso-max-size")]
    pub fn set_gso_max_size(&self, gso_max_size: i64) {
        ObjectExt::set_property(self,"gso-max-size", gso_max_size)
    }

    /// The size of the transmit queue for the device, in number of packets. The value
    /// must be between 0 and 4294967295. When set to -1, the existing value is preserved.
    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "tx-queue-length")]
    pub fn set_tx_queue_length(&self, tx_queue_length: i64) {
        ObjectExt::set_property(self,"tx-queue-length", tx_queue_length)
    }

    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "gro-max-size")]
    pub fn connect_gro_max_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_gro_max_size_trampoline<F: Fn(&SettingLink) + 'static>(this: *mut ffi::NMSettingLink, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::gro-max-size".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_gro_max_size_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "gso-max-segments")]
    pub fn connect_gso_max_segments_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_gso_max_segments_trampoline<F: Fn(&SettingLink) + 'static>(this: *mut ffi::NMSettingLink, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::gso-max-segments".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_gso_max_segments_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "gso-max-size")]
    pub fn connect_gso_max_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_gso_max_size_trampoline<F: Fn(&SettingLink) + 'static>(this: *mut ffi::NMSettingLink, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::gso-max-size".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_gso_max_size_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    #[doc(alias = "tx-queue-length")]
    pub fn connect_tx_queue_length_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_tx_queue_length_trampoline<F: Fn(&SettingLink) + 'static>(this: *mut ffi::NMSettingLink, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::tx-queue-length".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_tx_queue_length_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

#[cfg(feature = "v1_44")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
impl Default for SettingLink {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`SettingLink`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct SettingLinkBuilder {
            builder: glib::object::ObjectBuilder<'static, SettingLink>,
        }

        impl SettingLinkBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The maximum size of a packet built by the Generic Receive Offload stack for
                            /// this device. The value must be between 0 and 4294967295. When set to -1, the
                            /// existing value is preserved.
                            #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    pub fn gro_max_size(self, gro_max_size: i64) -> Self {
                            Self { builder: self.builder.property("gro-max-size", gro_max_size), }
                        }

                            /// The maximum segments of a Generic Segment Offload packet the device should accept.
                            /// The value must be between 0 and 4294967295. When set to -1, the existing value
                            /// is preserved.
                            #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    pub fn gso_max_segments(self, gso_max_segments: i64) -> Self {
                            Self { builder: self.builder.property("gso-max-segments", gso_max_segments), }
                        }

                            /// The maximum size of a Generic Segment Offload packet the device should accept.
                            /// The value must be between 0 and 4294967295. When set to -1, the existing value
                            /// is preserved.
                            #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    pub fn gso_max_size(self, gso_max_size: i64) -> Self {
                            Self { builder: self.builder.property("gso-max-size", gso_max_size), }
                        }

                            /// The size of the transmit queue for the device, in number of packets. The value
                            /// must be between 0 and 4294967295. When set to -1, the existing value is preserved.
                            #[cfg(feature = "v1_44")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_44")))]
    pub fn tx_queue_length(self, tx_queue_length: i64) -> Self {
                            Self { builder: self.builder.property("tx-queue-length", tx_queue_length), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`SettingLink`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> SettingLink {
assert_initialized_main_thread!();
    self.builder.build() }
}
