// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT
#![allow(deprecated)]

use crate::{ffi,Setting};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    /// WiMax Settings
    ///
    /// ## Properties
    ///
    ///
    /// #### `mac-address`
    ///  If specified, this connection will only apply to the WiMAX device whose
    /// MAC address matches. This property does not change the MAC address of the
    /// device (known as MAC spoofing).
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `network-name`
    ///  Network Service Provider (NSP) name of the WiMAX network this connection
    /// should use.
    ///
    /// Readable | Writeable
    /// <details><summary><h4>Setting</h4></summary>
    ///
    ///
    /// #### `name`
    ///  The setting's name, which uniquely identifies the setting within the
    /// connection.  Each setting type has a name unique to that type, for
    /// example "ppp" or "802-11-wireless" or "802-3-ethernet".
    ///
    /// Readable
    /// </details>
    ///
    /// # Implements
    ///
    /// [`SettingExt`][trait@crate::prelude::SettingExt]
    #[doc(alias = "NMSettingWimax")]
    pub struct SettingWimax(Object<ffi::NMSettingWimax, ffi::NMSettingWimaxClass>) @extends Setting;

    match fn {
        type_ => || ffi::nm_setting_wimax_get_type(),
    }
}

impl SettingWimax {
    /// Creates a new #NMSettingWimax object with default values.
    ///
    /// # Deprecated since 1.2
    ///
    /// WiMAX is no longer supported.
    ///
    /// # Returns
    ///
    /// the new empty #NMSettingWimax object
    #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    #[allow(deprecated)]
    #[doc(alias = "nm_setting_wimax_new")]
    pub fn new() -> SettingWimax {
        assert_initialized_main_thread!();
        unsafe {
            Setting::from_glib_full(ffi::nm_setting_wimax_new()).unsafe_cast()
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`SettingWimax`] objects.
            ///
            /// This method returns an instance of [`SettingWimaxBuilder`](crate::builders::SettingWimaxBuilder) which can be used to create [`SettingWimax`] objects.
            pub fn builder() -> SettingWimaxBuilder {
                SettingWimaxBuilder::new()
            }
        

    /// Returns the MAC address of a WiMAX device which this connection is locked
    /// to.
    ///
    /// # Deprecated since 1.2
    ///
    /// WiMAX is no longer supported.
    ///
    /// # Returns
    ///
    /// the MAC address
    #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    #[allow(deprecated)]
    #[doc(alias = "nm_setting_wimax_get_mac_address")]
    #[doc(alias = "get_mac_address")]
    #[doc(alias = "mac-address")]
    pub fn mac_address(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_setting_wimax_get_mac_address(self.to_glib_none().0))
        }
    }

    /// Returns the WiMAX NSP name (ex "Sprint" or "CLEAR") which identifies the
    /// specific WiMAX network this setting describes a connection to.
    ///
    /// # Deprecated since 1.2
    ///
    /// WiMAX is no longer supported.
    ///
    /// # Returns
    ///
    /// the WiMAX NSP name
    #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    #[allow(deprecated)]
    #[doc(alias = "nm_setting_wimax_get_network_name")]
    #[doc(alias = "get_network_name")]
    #[doc(alias = "network-name")]
    pub fn network_name(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_setting_wimax_get_network_name(self.to_glib_none().0))
        }
    }

    /// If specified, this connection will only apply to the WiMAX device whose
    /// MAC address matches. This property does not change the MAC address of the
    /// device (known as MAC spoofing).
    ///
    /// # Deprecated since 1.2
    ///
    /// WiMAX is no longer supported.
    #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    #[doc(alias = "mac-address")]
    pub fn set_mac_address(&self, mac_address: Option<&str>) {
        ObjectExt::set_property(self,"mac-address", mac_address)
    }

    /// Network Service Provider (NSP) name of the WiMAX network this connection
    /// should use.
    ///
    /// # Deprecated since 1.2
    ///
    /// WiMAX is no longer supported.
    #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    #[doc(alias = "network-name")]
    pub fn set_network_name(&self, network_name: Option<&str>) {
        ObjectExt::set_property(self,"network-name", network_name)
    }

    #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    #[doc(alias = "mac-address")]
    pub fn connect_mac_address_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_mac_address_trampoline<F: Fn(&SettingWimax) + 'static>(this: *mut ffi::NMSettingWimax, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::mac-address".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_mac_address_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    #[doc(alias = "network-name")]
    pub fn connect_network_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_network_name_trampoline<F: Fn(&SettingWimax) + 'static>(this: *mut ffi::NMSettingWimax, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::network-name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_network_name_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl Default for SettingWimax {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`SettingWimax`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct SettingWimaxBuilder {
            builder: glib::object::ObjectBuilder<'static, SettingWimax>,
        }

        impl SettingWimaxBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// If specified, this connection will only apply to the WiMAX device whose
                            /// MAC address matches. This property does not change the MAC address of the
                            /// device (known as MAC spoofing).
                            /// WiMAX is no longer supported.
                            #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    pub fn mac_address(self, mac_address: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("mac-address", mac_address.into()), }
                        }

                            /// Network Service Provider (NSP) name of the WiMAX network this connection
                            /// should use.
                            /// WiMAX is no longer supported.
                            #[cfg_attr(feature = "v1_2", deprecated = "Since 1.2")]
    pub fn network_name(self, network_name: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("network-name", network_name.into()), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`SettingWimax`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> SettingWimax {
assert_initialized_main_thread!();
    self.builder.build() }
}
