// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Setting};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    /// OLPC Wireless Mesh Settings
    ///
    /// ## Properties
    ///
    ///
    /// #### `channel`
    ///  Channel on which the mesh network to join is located.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `dhcp-anycast-address`
    ///  Anycast DHCP MAC address used when requesting an IP address via DHCP.
    /// The specific anycast address used determines which DHCP server class
    /// answers the request.
    ///
    /// This is currently only implemented by dhclient DHCP plugin.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `ssid`
    ///  SSID of the mesh network to join.
    ///
    /// Readable | Writeable
    /// <details><summary><h4>Setting</h4></summary>
    ///
    ///
    /// #### `name`
    ///  The setting's name, which uniquely identifies the setting within the
    /// connection.  Each setting type has a name unique to that type, for
    /// example "ppp" or "802-11-wireless" or "802-3-ethernet".
    ///
    /// Readable
    /// </details>
    ///
    /// # Implements
    ///
    /// [`SettingExt`][trait@crate::prelude::SettingExt]
    #[doc(alias = "NMSettingOlpcMesh")]
    pub struct SettingOlpcMesh(Object<ffi::NMSettingOlpcMesh, ffi::NMSettingOlpcMeshClass>) @extends Setting;

    match fn {
        type_ => || ffi::nm_setting_olpc_mesh_get_type(),
    }
}

impl SettingOlpcMesh {
    /// Creates a new #NMSettingOlpcMesh object with default values.
    ///
    /// # Returns
    ///
    /// the new empty #NMSettingOlpcMesh object
    #[doc(alias = "nm_setting_olpc_mesh_new")]
    pub fn new() -> SettingOlpcMesh {
        assert_initialized_main_thread!();
        unsafe {
            Setting::from_glib_full(ffi::nm_setting_olpc_mesh_new()).unsafe_cast()
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`SettingOlpcMesh`] objects.
            ///
            /// This method returns an instance of [`SettingOlpcMeshBuilder`](crate::builders::SettingOlpcMeshBuilder) which can be used to create [`SettingOlpcMesh`] objects.
            pub fn builder() -> SettingOlpcMeshBuilder {
                SettingOlpcMeshBuilder::new()
            }
        

    #[doc(alias = "nm_setting_olpc_mesh_get_channel")]
    #[doc(alias = "get_channel")]
    pub fn channel(&self) -> u32 {
        unsafe {
            ffi::nm_setting_olpc_mesh_get_channel(self.to_glib_none().0)
        }
    }

    #[doc(alias = "nm_setting_olpc_mesh_get_dhcp_anycast_address")]
    #[doc(alias = "get_dhcp_anycast_address")]
    #[doc(alias = "dhcp-anycast-address")]
    pub fn dhcp_anycast_address(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_setting_olpc_mesh_get_dhcp_anycast_address(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "nm_setting_olpc_mesh_get_ssid")]
    //#[doc(alias = "get_ssid")]
    //pub fn ssid(&self) -> /*Ignored*/glib::Bytes {
    //    unsafe { TODO: call ffi:nm_setting_olpc_mesh_get_ssid() }
    //}

    /// Channel on which the mesh network to join is located.
    pub fn set_channel(&self, channel: u32) {
        ObjectExt::set_property(self,"channel", channel)
    }

    /// Anycast DHCP MAC address used when requesting an IP address via DHCP.
    /// The specific anycast address used determines which DHCP server class
    /// answers the request.
    ///
    /// This is currently only implemented by dhclient DHCP plugin.
    #[doc(alias = "dhcp-anycast-address")]
    pub fn set_dhcp_anycast_address(&self, dhcp_anycast_address: Option<&str>) {
        ObjectExt::set_property(self,"dhcp-anycast-address", dhcp_anycast_address)
    }

    //pub fn set_ssid(&self, ssid: /*Ignored*/Option<&glib::Bytes>) {
    //    ObjectExt::set_property(self,"ssid", ssid)
    //}

    #[doc(alias = "channel")]
    pub fn connect_channel_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_channel_trampoline<F: Fn(&SettingOlpcMesh) + 'static>(this: *mut ffi::NMSettingOlpcMesh, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::channel".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_channel_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "dhcp-anycast-address")]
    pub fn connect_dhcp_anycast_address_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_dhcp_anycast_address_trampoline<F: Fn(&SettingOlpcMesh) + 'static>(this: *mut ffi::NMSettingOlpcMesh, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::dhcp-anycast-address".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_dhcp_anycast_address_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "ssid")]
    pub fn connect_ssid_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_ssid_trampoline<F: Fn(&SettingOlpcMesh) + 'static>(this: *mut ffi::NMSettingOlpcMesh, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::ssid".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_ssid_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl Default for SettingOlpcMesh {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`SettingOlpcMesh`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct SettingOlpcMeshBuilder {
            builder: glib::object::ObjectBuilder<'static, SettingOlpcMesh>,
        }

        impl SettingOlpcMeshBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// Channel on which the mesh network to join is located.
                            pub fn channel(self, channel: u32) -> Self {
                            Self { builder: self.builder.property("channel", channel), }
                        }

                            /// Anycast DHCP MAC address used when requesting an IP address via DHCP.
                            /// The specific anycast address used determines which DHCP server class
                            /// answers the request.
                            ///
                            /// This is currently only implemented by dhclient DHCP plugin.
                            pub fn dhcp_anycast_address(self, dhcp_anycast_address: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("dhcp-anycast-address", dhcp_anycast_address.into()), }
                        }

                            //pub fn ssid(self, ssid: /*Ignored*/&glib::Bytes) -> Self {
                        //    Self { builder: self.builder.property("ssid", ssid), }
                        //}

    // rustdoc-stripper-ignore-next
    /// Build the [`SettingOlpcMesh`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> SettingOlpcMesh {
assert_initialized_main_thread!();
    self.builder.build() }
}
