// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir
// from gtk-girs (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi,Setting,SettingWirelessSecurityWpsMethod};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "NMSettingWifiP2P")]
    pub struct SettingWifiP2P(Object<ffi::NMSettingWifiP2P, ffi::NMSettingWifiP2PClass>) @extends Setting;

    match fn {
        type_ => || ffi::nm_setting_wifi_p2p_get_type(),
    }
}

impl SettingWifiP2P {
    #[doc(alias = "nm_setting_wifi_p2p_new")]
    pub fn new() -> SettingWifiP2P {
        assert_initialized_main_thread!();
        unsafe {
            Setting::from_glib_full(ffi::nm_setting_wifi_p2p_new()).unsafe_cast()
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`SettingWifiP2P`] objects.
            ///
            /// This method returns an instance of [`SettingWifiP2PBuilder`](crate::builders::SettingWifiP2PBuilder) which can be used to create [`SettingWifiP2P`] objects.
            pub fn builder() -> SettingWifiP2PBuilder {
                SettingWifiP2PBuilder::new()
            }
        

    #[doc(alias = "nm_setting_wifi_p2p_get_peer")]
    #[doc(alias = "get_peer")]
    pub fn peer(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::nm_setting_wifi_p2p_get_peer(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "nm_setting_wifi_p2p_get_wfd_ies")]
    //#[doc(alias = "get_wfd_ies")]
    //#[doc(alias = "wfd-ies")]
    //pub fn wfd_ies(&self) -> /*Ignored*/glib::Bytes {
    //    unsafe { TODO: call ffi:nm_setting_wifi_p2p_get_wfd_ies() }
    //}

    #[doc(alias = "nm_setting_wifi_p2p_get_wps_method")]
    #[doc(alias = "get_wps_method")]
    #[doc(alias = "wps-method")]
    pub fn wps_method(&self) -> SettingWirelessSecurityWpsMethod {
        unsafe {
            from_glib(ffi::nm_setting_wifi_p2p_get_wps_method(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    pub fn set_peer(&self, peer: Option<&str>) {
        ObjectExt::set_property(self,"peer", peer)
    }

    //#[cfg(feature = "v1_16")]
    //#[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    //#[doc(alias = "wfd-ies")]
    //pub fn set_wfd_ies(&self, wfd_ies: /*Ignored*/Option<&glib::Bytes>) {
    //    ObjectExt::set_property(self,"wfd-ies", wfd_ies)
    //}

    #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    #[doc(alias = "wps-method")]
    pub fn set_wps_method(&self, wps_method: u32) {
        ObjectExt::set_property(self,"wps-method", wps_method)
    }

    #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    #[doc(alias = "peer")]
    pub fn connect_peer_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_peer_trampoline<F: Fn(&SettingWifiP2P) + 'static>(this: *mut ffi::NMSettingWifiP2P, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::peer".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_peer_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    #[doc(alias = "wfd-ies")]
    pub fn connect_wfd_ies_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_wfd_ies_trampoline<F: Fn(&SettingWifiP2P) + 'static>(this: *mut ffi::NMSettingWifiP2P, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::wfd-ies".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_wfd_ies_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    #[doc(alias = "wps-method")]
    pub fn connect_wps_method_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_wps_method_trampoline<F: Fn(&SettingWifiP2P) + 'static>(this: *mut ffi::NMSettingWifiP2P, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::wps-method".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_wps_method_trampoline::<F> as *const ())), Box_::into_raw(f))
        }
    }
}

#[cfg(feature = "v1_16")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
impl Default for SettingWifiP2P {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`SettingWifiP2P`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct SettingWifiP2PBuilder {
            builder: glib::object::ObjectBuilder<'static, SettingWifiP2P>,
        }

        impl SettingWifiP2PBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    pub fn peer(self, peer: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("peer", peer.into()), }
                        }

                        //    #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    //pub fn wfd_ies(self, wfd_ies: /*Ignored*/&glib::Bytes) -> Self {
                        //    Self { builder: self.builder.property("wfd-ies", wfd_ies), }
                        //}

                            #[cfg(feature = "v1_16")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_16")))]
    pub fn wps_method(self, wps_method: u32) -> Self {
                            Self { builder: self.builder.property("wps-method", wps_method), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`SettingWifiP2P`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> SettingWifiP2P {
assert_initialized_main_thread!();
    self.builder.build() }
}
